### ISSUE TITLE
Complete support for all XZ filters

### ISSUE THREAD

**Issue by xi2** [xi2/xz#1]
For full XZ support, package xz is currently missing the following features:

  * ~~Support for full length filter chains (up to 4 filters)~~
  * ~~Support for the "delta" filter~~
  * ~~Support for a non-zero start offset for BCJ filters~~

These features appear to be little used, but xz should support them ASAP so that package users can add "xz support" to their programs without needing to specify caveats about subformats.

Also test files should be added exercising all the above.

@klauspost

**Comment by klauspost** [comment]
Awesome!!!
